version: '3'

services: 
  crawler:
    mem_limit: 512m
    mem_reservation: 128m
    cpus: 0.5
    build: .
    ports:
    - "9080:9080"
    volumes:
      - .:/usr/src/app # Make sure it connects the host with the container for the update